# Generated by Django 5.1.6 on 2025-02-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_brand_alter_motorcycle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='motorcycles/'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
